;==============================================================================
;
; ModernUI Library v0.0.0.6
;
; Copyright (c) 2019 by fearless
;
; All Rights Reserved
;
; http://github.com/mrfearless/ModernUI
;
;
; This software is provided 'as-is', without any express or implied warranty. 
; In no event will the author be held liable for any damages arising from the 
; use of this software.
;
; Permission is granted to anyone to use this software for any non-commercial 
; program. If you use the library in an application, an acknowledgement in the
; application or documentation is appreciated but not required. 
;
; You are allowed to make modifications to the source code, but you must leave
; the original copyright notices intact and not misrepresent the origin of the
; software. It is not allowed to claim you wrote the original software. 
; Modified files must have a clear notice that the files are modified, and not
; in the original state. This includes the name of the person(s) who modified 
; the code. 
;
; If you want to distribute or redistribute any portion of this package, you 
; will need to include the full package in it's original state, including this
; license and all the copyrights.  
;
; While distributing this package (in it's original state) is allowed, it is 
; not allowed to charge anything for this. You may not sell or include the 
; package in any commercial package without having permission of the author. 
; Neither is it allowed to redistribute any of the package's components with 
; commercial applications.
;
;==============================================================================

; ModernUI x86 Library:
include ModernUI.inc

; ModernUI Controls:
include ModernUI_Button.inc
include ModernUI_CaptionBar.inc
include ModernUI_Checkbox.inc
include ModernUI_ProgressBar.inc
include ModernUI_ProgressDots.inc
include ModernUI_SmartPanel.inc
include ModernUI_Spinner.inc
include ModernUI_Text.inc
include ModernUI_Tooltip.inc
include ModernUI_TrayMenu.inc


